//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KelimeOyunuProje.Entitiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KelimeOgreniyorumDBEntities : DbContext
    {
        public KelimeOgreniyorumDBEntities()
            : base("name=KelimeOgreniyorumDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLKATEGORI> TBLKATEGORIs { get; set; }
        public virtual DbSet<TBLKISILER> TBLKISILERs { get; set; }
        public virtual DbSet<TBLOYUNLAR> TBLOYUNLARs { get; set; }
        public virtual DbSet<TBLMESAJ> TBLMESAJs { get; set; }
    }
}
