//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KelimeOyunuProje.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKISILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKISILER()
        {
            this.TBLOYUNLARs = new HashSet<TBLOYUNLAR>();
        }
    
        public int KisiId { get; set; }
        public string KisiAd { get; set; }
        public string KisiSoyad { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLOYUNLAR> TBLOYUNLARs { get; set; }
    }
}
