//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KelimeOyunuProje.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOYUNLAR
    {
        public int ID { get; set; }
        public string OyunAdi { get; set; }
        public string OyunAciklama { get; set; }
        public string OyunLink { get; set; }
        public string OyunResim { get; set; }
        public Nullable<System.DateTime> OyunTarih { get; set; }
        public Nullable<int> OyunuYapan { get; set; }
        public Nullable<int> OyunKategori { get; set; }
    
        public virtual TBLKATEGORI TBLKATEGORI { get; set; }
        public virtual TBLKISILER TBLKISILER { get; set; }
    }
}
